[project]
name = "library-manager-supabase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "pyarrow==16.0.0",
    "streamlit==1.37.1",
]
